name: Auto Update Parcheggi

on:
  schedule:
    - cron: '0 * * * *' # Gira ogni ora
  workflow_dispatch: # Permette l'avvio manuale

jobs:
  build:
    runs-on: ubuntu-latest
    # Aggiungiamo i permessi espliciti per scrivere nel repository
    permissions:
      contents: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        run: python motore_db.py

      - name: Save changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          # Forza l'aggiunta del file db se fosse nel gitignore
          git add -f storico_parcheggi.db 
          git commit -m "Aggiornamento automatico database: $(date)" || echo "No changes to commit"
          git push
